---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Paloalto provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['paloalto'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    - name: Create admin user for manual changes
      paloaltonetworks.panos.panos_administrator:
        provider: '{{ panos_provider }}'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        superuser: true

    # HTTP Config Server Profile
    # https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/config-log-fields 
    - name: Create a Config HTTP Server Profile for Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ config_profile_name }}"
        config_name: "{{ config_profile_name }}"
        config_uri_format: '/test'
        config_payload: >
          {
              "receive_time": "$receive_time",
              "device_name": "$device_name",
              "serial": "$serial",
              "host": "$host",
              "seqno": "$seqno",
              "dg_id": "$dg_id",
              "type": "$type",
              "subtype": "$subtype",
              "vsys": "$vsys",
              "vsys_name": "$vsys_name",
              "admin": "$admin",
              "client": "$client",
              "cmd": "$cmd",
              "path": "$path",
              "result": "$result",
              "comment": "$comment",
              "actionflags": "$actionflags",
              "before_change_detail": "$before-change-detail",
              "after_change_detail": "$after-change-detail"
          }

    # HTTP System Server Profile
    # https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/system-log-fields
    - name: Create a System HTTP Server Profile for Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ system_profile_name }}"
        system_name: "{{ system_profile_name }}"
        system_uri_format: '/test'
        system_payload: >
          {
              "receive_time": "$receive_time",
              "device_name": "$device_name",
              "serial": "$serial",
              "seqno": "$seqno",
              "type": "$type",
              "subtype": "$subtype",
              "vsys": "$vsys",
              "vsys_name": "$vsys_name",
              "event_id": "$event_id",
              "object": "$object",
              "module": "$module",
              "severity": "$severity",
              "opaque": "$opaque",
              "actionflags": "$actionflags",
          }

    - name: Create Config HTTP server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ config_profile_name }}'
        name: '{{ config_http_server_name }}'
        address: "{{ http_address }}"
        protocol: "{{ config_http_protocol }}"
        http_method: "{{ config_http_method }}"
        http_port: "{{ config_http_port }}"

    - name: Create System HTTP server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ system_profile_name }}'
        name: '{{ system_http_server_name }}'
        address: "{{ http_address }}"
        protocol: "{{ system_http_protocol }}"
        http_method: "{{ system_http_method }}"
        http_port: "{{ system_http_port }}"

    - name: Add a HTTP header to Config HTTP Server Profile
      paloaltonetworks.panos.panos_http_profile_header:
        provider: '{{ panos_provider }}'
        http_profile: '{{ config_profile_name }}'
        log_type: 'config'
        header: 'Content-Type'
        value: 'application/json'

    - name: Add a HTTP header to System HTTP Server Profile
      paloaltonetworks.panos.panos_http_profile_header:
        provider: '{{ panos_provider }}'
        http_profile: '{{ system_profile_name }}'
        log_type: 'system'
        header: 'Content-Type'
        value: 'application/json'

    - name: Add a param to the Config Log Type
      paloaltonetworks.panos.panos_http_profile_param:
        provider: '{{ panos_provider }}'
        http_profile: '{{ config_profile_name }}'
        log_type: 'config'
        param: 'serial'
        value: '$serial'

    - name: Add a param to the System Log Type
      paloaltonetworks.panos.panos_http_profile_param:
        provider: '{{ panos_provider }}'
        http_profile: '{{ system_profile_name }}'
        log_type: 'system'
        param: 'serial'
        value: '$serial'

    # Log Config Forwarding Profile
    - name: Create Config Log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: '{{ config_forwarding_profile_name }}'

    # Log System Forwarding Profile
    - name: Create log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: '{{ system_forwarding_profile_name }}'

    - name: Create Config log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: '{{ config_forwarding_profile_name }}'
        name: '{{ config_forwarding_profile_name_match_list }}'
        #log_type: traffic  # default
        filter: '{{ config_log_filter }}'
        http_profiles: ['{{ config_profile_name }}']

    - name: Create System log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: '{{ system_forwarding_profile_name }}'
        name: '{{ system_forwarding_profile_name_match_list }}'
        #log_type: traffic  # default
        filter: '{{ system_log_filter }}'
        http_profiles: ['{{ system_profile_name }}']

    # set shared log-settings config match-list "Config Logs" filter "All Logs" send-http {{ profile_name }}
    - name: Forward Config Logs to EDA source
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ panos_provider }}'
        cmd: set  # default
        xpath: "/config/shared/log-settings/config/match-list"
        element: |
          <entry name="{{ config_log_name }}">
            <send-http>
              <member>{{ config_profile_name }}</member>
            </send-http>
            <filter>{{ log_filter }}</filter>
          </entry>

    - name: Forward System Logs to EDA source
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ panos_provider }}'
        cmd: set  # default
        xpath: "/config/shared/log-settings/system/match-list"
        element: |
          <entry name="{{ system_log_name }}">
            <send-http>
              <member>{{ system_profile_name }}</member>
            </send-http>
            <filter>{{ system_log_filter }}</filter>
          </entry>

    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"
