---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

    
# RHEL Configs
- name: AWS RHEL config
  hosts: rhel
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/bin/python3 # Why needed?
  tasks:
    - name: Attach Red Hat subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ subscription_user }}"
        password: "{{ subscription_pass }}"
        pool_ids: "{{ rh_subs_pool_id }}"
      become: true

    - name: Install Software
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - firewalld
          - httpd
          - at
      become: yes

    - name: Open port TCP 80
      ansible.posix.firewalld:
        port: http/tcp
        permanent: yes
        state: enabled
      become: true

    - name: Open port TCP 443
      ansible.posix.firewalld:
        port: https/tcp
        permanent: yes
        state: enabled
      become: true

    - name: Copy index.html template to webserver
      ansible.builtin.template:
        src: templates/rhel-index.html.j2
        dest: /var/www/html/index.html
        owner: apache
        mode: "0644"
      vars:
        title: "Paloalto Demo"
        body: "Hi, I am RHEL VM on Paloalto Demo"
      become: yes

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: yes
        state: restarted
      become: true

    - name: Restart atd
      ansible.builtin.service:
        name: atd
        enabled: yes
        state: restarted
      become: true

    - name: Restart httpd server 
      ansible.builtin.service: 
        name: httpd
        enabled: yes
        state: restarted
      become: yes
    
    - name: Dettach Red Hat subscription
      community.general.redhat_subscription:
        state: absent
        username: "{{ subscription_user }}"
        password: "{{ subscription_pass }}"
        pool_ids: "{{ rh_subs_pool_id }}"
      become: true

    # - name: Disable connection on boot (NOT WORKING!)
    #   community.general.nmcli:
    #     conn_name: eth0
    #     type: ethernet
    #     ifname: eth0
    #     state: down
    #   become: true
      # async: 10      # Maximum time allowed for the task to exist
      # poll: 0        # Fire and forget: don't wait for a response
      # ignore_errors: yes

    - name: Disable connection on boot (1 minute after)
      ansible.builtin.shell:
        cmd: echo 'sudo nmcli connection down "System eth0"' | at now + 1 minute

    - name: Get Paloalto EN2 Public IP
      set_fact:
        paloalto_en2_public_ip: "{{ item.private_ip_addresses[0].association.public_dns_name }}"
      loop: "{{ hostvars[groups['paloalto'][0]].network_interfaces }}"
      when: item.attachment.device_index == 2

    - name: Debug URL for Vulnerability testing
      debug:
        msg: "URL RHEL Web Server Acess: http://{{ paloalto_en2_public_ip }}"


# RHEL JUMP Configs
- name: AWS RHEL JUMP config
  hosts: rhel_jump
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/bin/python3 # Why needed?
  tasks:
    - name: Attach Red Hat subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ subscription_user }}"
        password: "{{ subscription_pass }}"
        pool_ids: "{{ rh_subs_pool_id }}"
      become: true

    - name: Install Software
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - firewalld
          - httpd
      become: yes

    - name: Open port TCP 80
      ansible.posix.firewalld:
        port: http/tcp
        permanent: yes
        state: enabled
      become: true

    - name: Open port TCP 443
      ansible.posix.firewalld:
        port: https/tcp
        permanent: yes
        state: enabled
      become: true

    - name: Copy index.html template to webserver
      ansible.builtin.template:
        src: templates/rhel-jump-index.html.j2
        dest: /var/www/html/index.html
        owner: apache
        mode: "0644"
      vars:
        title: "Paloalto Demo"
        body: "Hi, I am RHEL JUMP VM on Paloalto Demo"
      become: yes

    - name: Get Virus from Source
      ansible.builtin.uri:
        url: "https://www.eicar.org/download/eicar.com.txt"
        return_content: true
        method: GET
      register: result

    - name: Copy eicar.com.txt file to webserver
      ansible.builtin.copy:
        content: "{{ result.content }}"
        dest: /var/www/html/eicar.com.txt
        owner: apache
        mode: "0644"
      become: yes

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: yes
        state: restarted
      become: true

    - name: Restart httpd server 
      ansible.builtin.service: 
        name: httpd
        enabled: yes
        state: restarted
      become: yes
    
    - name: Dettach Red Hat subscription
      community.general.redhat_subscription:
        state: absent
        username: "{{ subscription_user }}"
        password: "{{ subscription_pass }}"
        pool_ids: "{{ rh_subs_pool_id }}"
      become: true

    - name: Debug URL for Anti-Virus testing
      debug:
        msg: "Virus URL: curl http://{{ inventory_hostname }}/eicar.com.txt"
