---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Delete Paloalto provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['paloalto'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    # delete shared log-settings config match-list "Config Logs" filter "All Logs" send-http {{ config_profile_name }}
    - name: Delete Forward Config Logs to EDA source
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ panos_provider }}'
        cmd: delete  # default
        xpath: "/config/shared/log-settings/config/match-list"
        element: |
          <entry name="{{ config_log_name }}">
            <send-http>
              <member>{{ config_profile_name }}</member>
            </send-http>
            <filter>{{ config_log_filter }}</filter>
          </entry>

    # delete shared log-settings system match-list "System Logs" filter "All Logs" send-http {{ system_profile_name }}
    - name: Delete Forward System Logs to EDA source
      paloaltonetworks.panos.panos_type_cmd:
        provider: '{{ panos_provider }}'
        cmd: delete  # default
        xpath: "/config/shared/log-settings/system/match-list"
        element: |
          <entry name="{{ system_log_name }}">
            <send-http>
              <member>{{ system_profile_name }}</member>
            </send-http>
            <filter>{{ system_log_filter }}</filter>
          </entry>

    - name: Delete Config log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: '{{ config_forwarding_profile_name }}'
        name: '{{ config_forwarding_profile_name_match_list }}'
        #log_type: traffic  # default
        filter: '{{ config_log_filter }}'
        http_profiles: ['{{ config_profile_name }}']
        state: absent

    - name: Delete System log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: '{{ system_forwarding_profile_name }}'
        name: '{{ system_forwarding_profile_name_match_list }}'
        #log_type: traffic  # default
        filter: '{{ system_log_filter }}'
        http_profiles: ['{{ system_profile_name }}']
        state: absent

    # Config Log Forwarding Profile
    - name: Delete Config log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: '{{ config_forwarding_profile_name }}'
        state: absent

    # System Log Forwarding Profile
    - name: Delete System log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: '{{ system_forwarding_profile_name }}'
        state: absent

    # HTTP Server Profile
    # https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/config-log-fields 
    - name: Delete a HTTP Server Profile for Config Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ config_profile_name }}"
        config_name: "{{ config_profile_name }}"
        config_uri_format: '/test'
        config_payload: >
          {
              "receive_time": "$receive_time",
              "device_name": "$device_name",
              "serial": "$serial",
              "host": "$host",
              "seqno": "$seqno",
              "type": "$type",
              "dg_id": "$dg_id",
              "type": "$type",
              "subtype": "$subtype",
              "vsys": "$vsys",
              "vsys_name": "$vsys_name",
              "admin": "$admin",
              "client": "$client",
              "cmd": "$cmd",
              "path": "$path",
              "result": "$result",
              "comment": "$comment",
              "before_change_detail": "$before-change-detail",
              "after_change_detail": "$after-change-detail"
          }
        state: absent

    # HTTP System Server Profile
    # https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/system-log-fields
    - name: Create a HTTP Server Profile for System Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ system_profile_name }}"
        system_name: "{{ system_profile_name }}"
        system_uri_format: '/test'
        system_payload: >
          {
              "receive_time": "$receive_time",
              "device_name": "$device_name",
              "serial": "$serial",
              "seqno": "$seqno",
              "type": "$type",
              "subtype": "$subtype",
              "vsys": "$vsys",
              "vsys_name": "$vsys_name",
              "eventid": "$eventid",
              "object": "$object",
              "module": "$module",
              "severity": "$severity",
              "opaque": "$opaque",
              "actionflags": "$actionflags",
          }
        state: absent

    - name: Delete Config HTTP Server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ config_profile_name }}'
        name: '{{ config_http_server_name }}'
        address: "{{ http_address }}"
        protocol: "{{ config_http_protocol }}"
        http_method: "{{ config_http_method }}"
        http_port: "{{ config_http_port }}"
        state: absent

    - name: Delete System HTTP Server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ config_profile_name }}'
        name: '{{ config_http_server_name }}'
        address: "{{ http_address }}"
        protocol: "{{ config_http_protocol }}"
        http_method: "{{ config_http_method }}"
        http_port: "{{ config_http_port }}"
        state: absent

    - name: Delete admin user for manual changes
      paloaltonetworks.panos.panos_administrator:
        provider: '{{ panos_provider }}'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        superuser: true
        state: absent

  # NEW USE CASES
    - name: Delete Policy Rule for Virus detection and Vulnerability protection 
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ panos_provider }}"
        rule_name: "Virus and Vulnerability"
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: ['any']
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['service-http','service-https']
        action: allow
        antivirus: default
        vulnerability: default
        state: absent

    - name: Delete NAT Policy Rule (OUT -> IN)
      paloaltonetworks.panos.panos_nat_rule2:
        provider: '{{ panos_provider }}'
        name: 'NAT OUTIN'
        nat_type: 'ipv4'
        from_zones: ['public']
        to_zones: ['private']
        to_interface: 'any'
        service: 'any'
        source_addresses: ['any']
        #destination_addresses: '10.0.1.171' # NEED CHANGE TO DYNAMIC!
        #destination_translated_address: '10.0.2.184' # NEED CHANGE TO DYNAMIC!
        state: absent

    - name: Delete NAT Policy Rule (IN -> OUT)
      paloaltonetworks.panos.panos_nat_rule:
        provider: '{{ panos_provider }}'
        name: 'NAT INOUT'
        nat_type: 'ipv4'
        from_zones: ['private']
        to_zones: ['public']
        to_interface: 'any'
        service: 'any'
        source_addresses: ['any']
        destination_addresses: ['any']
        source_translation_type: 'dynamic-ip-and-port'
        source_translation_address_type: 'interface-address'
        source_translation_interface: 'ethernet1/2'
        state: absent

    - name: Delete Interfaces from default Virtual Router
      paloaltonetworks.panos.panos_virtual_router:
        provider: '{{ panos_provider }}'
        name: default
        interface: 
          - ethernet1/1
          - ethernet1/2
        state: absent

    - name: Disable DHCP client on ethernet1/1 in zone private
      paloaltonetworks.panos.panos_interface:
        provider: '{{ panos_provider }}'
        if_name: "ethernet1/1"
        enable_dhcp: true
        create_default_route: true
        management_profile: SSH_PING
        zone_name: "private"
        state: absent

    - name: Disable DHCP client on ethernet1/2 in zone public
      paloaltonetworks.panos.panos_interface:
        provider: '{{ panos_provider }}'
        if_name: "ethernet1/2"
        enable_dhcp: true
        create_default_route: true
        management_profile: SSH_PING
        zone_name: "public"
        state: absent

    - name: Delete management profile that allows ping and ssh
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ panos_provider }}'
        name: 'SSH_PING'
        ping: true
        ssh: true
        state: absent

    - name: Delete public zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ panos_provider }}'
        zone: 'public'
        mode: 'layer3'
        state: absent

    - name: Delete private zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ panos_provider }}'
        zone: 'private'
        mode: 'layer3'
        state: absent

    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"
      ignore_errors: true