---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Paloalto provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['paloalto'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
          
    - name: Rules Provisioning
      include_tasks: rule_main_delete.yml