---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Setup Paloalto provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['paloalto'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    - name: Hostvars
      debug:
        var: hostvars['localhost']

    - name: System Authentication
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Payload
      debug:
        var: hostvars['localhost']

    # # Slack Setup: https://www.youtube.com/shorts/jcPnBYB5qww 
    # - name: Send notification message via Slack
    #   community.general.slack:
    #     token: "{{ ansible_password }}"
    #     channel: "#ansible-demos"
    #     #channel: "#novo-canal"
    #     username: "Paloalto-Bot"
    #     #msg: "{{ payload }}"
    #     msg: "My message"
