---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Change Paloalto password
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

  # cat private-key.pem | ansible-vault encrypt_string  --stdin-name 'private_key' --output private-key.vault
  - ansible.builtin.include_vars: files/private-key.yml

  - debug:
      msg: "{{ private_key }}"

  - name: Copy using inline content
    ansible.builtin.copy:
      content: "{{ private_key }}"
      dest: /tmp/private-key.pem
      mode: '0600'


  # https://docs.paloaltonetworks.com/vm-series/11-1/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/deploy-the-vm-series-firewall-on-aws/launch-the-vm-series-firewall-on-aws
  - name: Set admin initial password
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no -i /tmp/private-key.pem admin@{{ groups['paloalto'][0] }}"
      responses:
        # admin@PA-VM# set mgt-config users admin password
        # Enter password   : 
        # Confirm password : 

        # [edit]                                                                                                       
        # admin@PA-VM#
        'admin@PA-VM>':
          - configure
        'admin@PA-VM#':
          - set mgt-config users admin password
        'Enter password':
          - "{{ new_password }}" 
        'Confirm password':
          - "{{ new_password }}"
        '[edit]':
          - exit
          - exit
    no_log: false # hide passwords on logs

  # - name: Run command
  #   ansible.builtin.raw: configure

  # - name: Run command
  #   ansible.builtin.command: exit

  # - name: Run command to change password
  #   ansible.builtin.command: "{{ item }}"
  #   loop:
  #     - configure
  #     # - set mgt-config users admin password
  #     # #- "set mgt-config users admin phash {{ password_hash }}"
  #     # - "Admin123$%&
  #     # - "Admin123$%&"
  #     - "exit"
  #     - "exit"
