---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Threat Virus Detection
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['paloalto'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    - name: Hostvars
      debug:
        var: hostvars['localhost']

    - name: THREAT DETECTION (virus) payload
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Create Address Group 'InOut Quarantine'
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ panos_provider }}"
        name: InOut Quarantine
        description: 'Questionable Address Group - isolate Virus Hosts'
        dynamic_value: 'inout_quarantine'
        state: present

    - name: Add Policy Rule to Dynamic Address Group
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ panos_provider }}"
        rule_name: "InOut Quarantine"
        description: "InOut Quarantine Dynamic User Group"
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: InOut Quarantine
        destination_ip: ['any']
        category: ['any']
        application: ['any']
        service: ['any']
        location: top
        action: deny
        state: merged

    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"

    - name: Add 'inout_quarantine' tag to Host {{ payload.src }}
      paloaltonetworks.panos.panos_registered_ip:
        provider: "{{ panos_provider }}"
        ips: "{{ payload.src }}"
        tags: inout_quarantine
        state: present

