---

- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (threat events)"
  hosts: "localhost"
  # Source PanOS config
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5002
        #type: threat
  # Rule system logs
  rules:
    - name: "Handle Threats - Virus Detection"
      #condition: event.payload.type == "THREAT" and event.payload.subtype == "virus"
      #condition: event.payload.type == event.payload.type
      actions:
        # Debug
        - debug: 
            var: event.payload
        - print_event:
            pretty: true
        # Notify Slack
        - run_job_template:
            organization: "Default"
            name: "AWS EDA Paloalto: Threat Virus"
